name = "sharecation-authentication"
compatibility_date = "2022-07-14"
usage_model = "unbound"
legacy_env = true

[vars]
ENVIRONMENT = ""

[[migrations]]
tag = "v1"
new_classes = ["RightsStorage"]
[[migrations]]
tag = "v2"
renamed_classes = [{from = "RightsStorage", to = "RolesStorage" }]

[env.development]
vars = { ENVIRONMENT = "development" }
kv_namespaces = [
    { binding = "COMMON", id = "31cfb304e7994d62b9d31321d3ca52bc", preview_id = "31cfb304e7994d62b9d31321d3ca52bc" },
    { binding = "AUTHENTICATION", id = "d63b4f16d315411aa89199e0b6a5a288", preview_id = "d63b4f16d315411aa89199e0b6a5a288" }
]
durable_objects.bindings = [
    { name = "ROLES_STORAGE", class_name = "RolesStorage" }
]

[env.production]
vars = { ENVIRONMENT = "production" }
kv_namespaces = [
    { binding = "COMMON", id = "9fd8a473258d4e9ca3d601b9bd74ebcf" },
    { binding = "AUTHENTICATION", id = "a7fb628fa0504ddebf9d44d1370b1dd6" }
]
durable_objects.bindings = [
    { name = "ROLES_STORAGE", class_name = "RolesStorage" }
]
