name = "sharecation-authentication-scheduled"
compatibility_date = "2022-01-17"
usage_model = "unbound"

[vars]
ENVIRONMENT = ""

[triggers]
crons = ["0 0 * * mon"]

[env.development]
vars = { ENVIRONMENT = "development" }
kv_namespaces = [
    { binding = "COMMON", id = "31cfb304e7994d62b9d31321d3ca52bc", preview_id = "31cfb304e7994d62b9d31321d3ca52bc" }
]

[env.production]
vars = { ENVIRONMENT = "production" }
kv_namespaces = [
    { binding = "COMMON", id = "9fd8a473258d4e9ca3d601b9bd74ebcf" }
]
