name = "sharecation-ping"
compatibility_date = "2022-04-01"
legacy_env = true
main = "./main.ts"

[vars]
ENVIRONMENT = ""

[env.testing]
vars = { ENVIRONMENT = "testing" }

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }
