name = "sharecation-groups"
compatibility_date = "2022-01-17"

[vars]
ENVIRONMENT = ""

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }
