export const COMMON_KV = {
  GOOGLE_VERIFYING_JWKS: 'GOOGLE_VERIFYING_JWKS:',
  GOOGLE_VERIFYING_JWK: (kid: string) =>
    `${COMMON_KV.GOOGLE_VERIFYING_JWKS}${kid}`,
  PUBLIC_JWKS: 'PUBLIC_JWKS:',
  PUBLIC_JWK: (kid: string) => `${COMMON_KV.PUBLIC_JWKS}${kid}`,
  PRIVATE_JWKS: 'PRIVATE_JWKS:',
  PRIVATE_JWK: (kid: string) => `${COMMON_KV.PRIVATE_JWKS}${kid}`,
  CURRENT_PRIVATE_JWK: 'CURRENT_PRIVATE_JWK',
};
