name: Admin

on:
  push:
    paths:
      - ./.github/**
      - admin/**
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache-dependency-path: admin/package-lock.json
          cache: 'npm'
      - run: cd admin && npm ci
      - run: cd admin && npm run build
