name: App

on:
  push:
    paths:
      - .github/**
      - app/**
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: cd app && flutter pub get
      - run: cd app && flutter build appbundle
