name: Proto

on:
  push:
    paths:
      - .github/**
      - proto/docker/**
  workflow_call:

env:
  IMAGE_NAME: donatowolfisberg/sharecation-proto-builder

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@2
        with:
          username: donatowolfisberg
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@4
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: tags
        run: echo ${{ steps.meta.outputs.tags }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@3
        with:
          context: ./proto/docker/
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}
